In [1]:
import numpy as np

from IPython.core.debugger import set_trace

In [2]:
def check_win(state, i, j):
    done = False
    done = check_up_down(state, i, j)
    if done:
        return done
    done = check_left_right(state, i, j)
    if done:
        return done
    done = check_right_diag(state, i, j)
    if done:
        return done
    return check_left_diag(state, i, j)

def check_up_down(state, i, j):
    num_in_a_row = 0
    for r in range(state.shape[0]):
        if state[r, j] == 0:
            num_in_a_row = 0
        else:
            num_in_a_row += 1
            if num_in_a_row == 4:
                return True
    return False

def check_left_right(state, i, j):
    num_in_a_row = 0
    for c in range(state.shape[1]):
        if state[i, c] == 0:
            num_in_a_row = 0
        else:
            num_in_a_row += 1
            if num_in_a_row == 4:
                return True
    return False

def check_right_diag(state, i, j):
    r = i
    c = j
    while r < state.shape[0]-1 and c > 0:
        r += 1
        c -= 1
    
    if c == 0:
        num_in_a_row = 0
        for c in range(state.shape[1]):
            if r < 0:
                break
            if state[r, c] == 0:
                num_in_a_row = 0
            else:
                num_in_a_row += 1
                if num_in_a_row == 4:
                    return True
            r -= 1
    else:
        num_in_a_row = 0
        for r in reversed(range(state.shape[0])):
            if c > state.shape[1]-1:
                break
            if state[r, c] == 0:
                num_in_a_row = 0
            else:
                num_in_a_row += 1
                if num_in_a_row == 4:
                    return True 
                
            c += 1
            
    return False

def check_left_diag(state, i, j):
    r = i
    c = j
    while r > 0 and c > 0:
        r -= 1
        c -= 1
    
    if c == 0:
        num_in_a_row = 0
        for c in range(state.shape[1]):
            if r > state.shape[0]-1:
                break
            if state[r, c] == 0:
                num_in_a_row = 0
            else:
                num_in_a_row += 1
                if num_in_a_row == 4:
                    return True
            r += 1
    else:
        num_in_a_row = 0
        for r in range(state.shape[0]):
            if c > state.shape[1]-1:
                break
            if state[r, c] == 0:
                num_in_a_row = 0
            else:
                num_in_a_row += 1
                if num_in_a_row == 4:
                    return True 
                
            c += 1
            
    return False

In [ ]:
udw = np.zeros((6, 7))
tuples_list = []
num = 5
for i, rev_i in zip(range(num), reversed(range(num))):
    tuples_list.extend([(i, rev_i)])
    tuples_list.extend([(rev_i, i)])
    rdw[tuples_list[i]] = 1
    rdw[tuples_list[i+1]] = 1

tuples_list = [(5, 3), (4, 4), (3, 5), (2, 6)]
for tup in tuples_list:
    rdw[tup] = 1

print(rdw)

for tup in tuples_list:
    assert check_right_diag(rdw, tup[0], tup[1])

In [7]:
rdw = np.zeros((6, 7))
# tuples_list = []
# num = 5
# for i, rev_i in zip(range(num), reversed(range(num))):
#     tuples_list.extend([(i, rev_i)])
#     tuples_list.extend([(rev_i, i)])
#     rdw[tuples_list[i]] = 1
#     rdw[tuples_list[i+1]] = 1

tuples_list = [(5, 3), (4, 4), (3, 5), (2, 6)]
for tup in tuples_list:
    rdw[tup] = 1

print(rdw)

for tup in tuples_list:
    assert check_right_diag(rdw, tup[0], tup[1])

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]]


In [171]:
right_diag_win = np.zeros((6, 7))
for i in range(4):
    right_diag_win[4-i, 5+i] = 1
print(right_diag_win)

for j in range(4):
    right_diag_win[j, 3-j] = 1
    print(right_diag_win)
    assert check_right_diag(right_diag_win, j, 3-j)

IndexError: index 7 is out of bounds for axis 1 with size 7

In [161]:
left_diag_win = np.zeros((6, 7))
for i in range(0, 4):
    left_diag_win[i, i+1] = 1
print(left_diag_win)
assert check_left_diag(left_diag_win, 0, 1)

[[ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [144]:
for i in reversed(range(6)):
    print(i)

5
4
3
2
1
0


In [126]:
left_diag_win = np.zeros((6, 7))
for i in range(4):
    left_diag_win[i, i] = 1
print(left_diag_win)
for i in range(1, 6):
    assert check_left_diag(left_diag_win, i, i)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [123]:
up_down_win = np.zeros((6, 7))
for i in range(4):
    up_down_win[i, 0] = 1
print(up_down_win)
for i in range(up_down_win.shape[0]-1):
    assert check_up_down(up_down_win, i, 0)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [125]:
left_right_win = np.zeros((6, 7))
for i in range(4):
    left_right_win[0, i] = 1
print(left_right_win)
for i in range(left_right_win.shape[1]-1):
    assert check_left_right(left_right_win, 0, i)

[[ 1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [78]:

def test_win_checkers():
    board = np.zeros((6, 7))
    
    left_win = np.copy(board)
    right_win = np.copy(board)
    up_win = np.copy(board)
    down_win = np.copy(board)
    left_up_diag_win = np.copy(board)
    right_up_diag_win = np.copy(board)
    left_down_diag_win = np.copy(board)
    right_down_diag_win = np.copy(board)
    
    left_win[0][:4] = 1; left_win #0, 3
    assert check_win(left_win, 0, 3)
    left_win[0][0] = 0
    assert not check_win(left_win, 0, 3)
    
    right_win[0][:4] = 1; right_win #0, 0
    assert(check_win(right_win, 0, 0))
    right_win[0][3] = 0
    assert not check_win(right_win, 0, 0)
    
    for i in range(4):
        up_win[i][0] = 1
    assert(check_win(up_win, 3, 0))
    up_win[0][0] = 0
    assert not check_win(up_win, 3, 0)
    
    for i in range(4):
        down_win[i][0] = 1
    assert(check_win(down_win, 0, 0))
    down_win[3][0] = 0
    assert not check_win(down_win, 0, 0)
    
    for i in range(4):
        left_up_diag_win[i, i] = 1
    assert(check_win(left_up_diag_win, 3, 3))
    left_up_diag_win[0][0] = 0
    assert not check_win(left_up_diag_win, 3, 3)
    
    for i in range(4):
        left_down_diag_win[i, 3-i] = 1
    assert(check_win(left_down_diag_win, 0, 3))
    left_down_diag_win[3][0] = 0
    assert not check_win(left_down_diag_win, 0, 3)
    
    for i in range(4):
        right_up_diag_win[3-i, i] = 1
    assert(check_win(right_up_diag_win, 3, 0))
    right_up_diag_win[0][3] = 0
    assert not check_win(right_up_diag_win, 3, 0)
    
    for i in range(4):
        right_down_diag_win[i, i] = 1
    assert check_win(right_down_diag_win, 0, 0)
    right_down_diag_win[3][3] = 0
    assert not check_win(right_down_diag_win, 0, 0)

In [79]:
test_win_checkers()

In [60]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [42]:
board = np.zeros((6, 7))
left_win = np.copy(board)

for i in range(left_win.shape[0]):
    for j in range(4):
        left_win[i, j:j+4] = 1
        print(left_win)
        assert check_win(left_win, i, 3+j)
        left_win[i, j:j+4] = 0

[[ 1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  0.  0.]
 [ 

In [41]:
board = np.zeros((6, 7))
right_win = np.copy(board)

for i in range(right_win.shape[0]):
    for j in range(4):
        right_win[i, j:j+4] = 1
        print(right_win)
        assert check_win(right_win, i, 3+j)
        right_win[i, j:j+4] = 0

[[ 1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  0.  0.]
 [ 